[package]
name = "llvm-passgen"
version = "0.1.0"
authors = ["William Woodruff <william@yossarian.net>"]
edition = "2018"
description = "A tool for quickly creating LLVM pass skeletons"
license = "MIT"
homepage = "https://github.com/woodruffw/llvm-passgen"

[badges]
travis-ci = { repository = "woodruffw/llvm-passgen", branch = "master" }
maintenance = { status = "experimental" }

[dependencies]
clap = "~2.33"
handlebars = "2.0.2"
rust-embed = "5.1.0"
serde = { version = "~1.0", features = ["derive"] }
