[package]
name = "llvm-passgen"
version = "0.2.1"
authors = ["William Woodruff <william@yossarian.net>"]
edition = "2018"
description = "A tool for quickly creating LLVM pass skeletons"
license-file = "LICENSE"
homepage = "https://github.com/woodruffw/llvm-passgen"

[package.metadata.release]
no-dev-version = true

[badges]
travis-ci = { repository = "woodruffw/llvm-passgen", branch = "master" }
maintenance = { status = "experimental" }

[dependencies]
clap = "~2.33"
handlebars = "3.5.1"
rust-embed = "5.6.0"
serde = { version = "~1.0", features = ["derive"] }
