name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Format
        run: cargo fmt && git diff --exit-code
      - name: Lint
        run: |
          rustup update
          rustup component add clippy
          cargo clippy
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Deps
      run: |
        sudo apt update
        sudo apt install -y llvm-dev
      if: matrix.os == 'ubuntu-latest'
    - name: Build
      run: cargo build
    - name: Test
      run: |
        bash test/test_llvm_passes.sh
